# Run from Project Root
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app
VOLUME /tmp

# Points to the config-server target folder
ARG JAR_FILE=back-end/config-server/target/*.jar

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
