# docker/backend/Dockerfile.eureka

FROM maven:3.9.4-eclipse-temurin-17 AS builder
WORKDIR /build
COPY backend/eureka-server/pom.xml .
COPY backend/eureka-server/src ./src
RUN mvn -B -DskipTests package

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /build/target/*.jar app.jar

EXPOSE 8761
ENTRYPOINT ["java", "-jar", "app.jar"]
