# docker/backend/Dockerfile.portfolio

FROM maven:3.9.4-eclipse-temurin-17 AS builder
WORKDIR /build
COPY backend/portfolio-service/pom.xml .
COPY backend/portfolio-service/src ./src
RUN mvn -B -DskipTests package

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /build/target/*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
