# docker/backend/Dockerfile.gateway

FROM maven:3.9.4-eclipse-temurin-17 AS builder
WORKDIR /build
COPY backend/api-gateway/pom.xml .
COPY backend/api-gateway/src ./src
RUN mvn -B -DskipTests package

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /build/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
